name: license
on:
  pull_request: {}
  push: {}

jobs:
  unit:
    name: check-license
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check license header
      run: hack/check-license.sh

