name: unit
on:
  pull_request: {}
  push: {}

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
    - name: Run unit tests
      run: go test -coverprofile=coverage.out -covermode=count -short ./...
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out

